FRAME 271 (83) CLUSTERS
========================
[NOTE] Active shapes: [32]
[VARS] All current shapes: []
Unoccluded_canon: {0: False, 1: False, 2: False, 3: True, 4: True, 5: False, 6: True, 7: True, 8: False, 9: False, 10: True, 11: True, 12: False, 13: False, 14: True, 15: True, 16: False, 17: False, 18: False, 19: True, 20: False, 21: False, 22: False, 23: False, 24: False, 25: False, 26: False, 27: False, 28: False, 29: False, 30: True, 31: True, 32: True, 33: False, 34: False, 35: False, 36: False}
[TIME] Processing frame 271 took 0.05s
[NOTE] Time bank saved to: motion_vectorization/outputs/shapes38_None/time_bank.pkl
/usr/local/lib/python3.11/dist-packages/torch/nn/functional.py:5015: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/workspace/MotionVectorization/motion_vectorization/shape_context.py:162: RuntimeWarning: invalid value encountered in divide
  add_cost = (Q_p2 - P_p)**2 / flag
/workspace/MotionVectorization/motion_vectorization/processor.py:78: RuntimeWarning: invalid value encountered in divide
  curr_in_prev = curr_warped_labels_mask @ prev_labels_mask.T / curr_total[..., None]
[ WARN:0@164.193] global loadsave.cpp:1063 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
/workspace/MotionVectorization/motion_vectorization/processor.py:76: RuntimeWarning: invalid value encountered in divide
  prev_in_curr = prev_warped_labels_mask @ curr_labels_mask.T / prev_total[..., None]
/workspace/MotionVectorization/motion_vectorization/shape_context.py:188: RuntimeWarning: invalid value encountered in divide
  r_array_n = r_array / r_array.mean()
OPTIM
Logging to motion_vectorization/logs/shapes38_optim_17654.out
2025-09-10 17:54:01.335262
Configs:
  video_file:   shapes38.mp4
  video_dir:    videos
  output_dir:   outputs
  suffix:       None
  config:       motion_vectorization/config/shapes38.json
  date: None
  frame_rate:   24
  subsample_rate:       1
  max_frames:   100
  start_frame:  0
  scale:        0.3
  bg_thresh:    0.1
  min_cluster_size:     30
  median_radius:        5
  cluster_eps:  5
  cluster_min_samples:  10
  bg_file:      None
  init_weight:  0.0
  init_thresh:  0.01
  num_match_shapes:     5
  match_radius: 120.0
  main_match_thresh:    0.5
  fallback_match_thresh:        0.5
  match_method: hu
  min_opt_size: 32
  blur_kernel:  1
  lr:   0.01
  p_weight:     0.1
  use_z:        True
  n_steps:      50
  use_gpu:      True
  bleed:        50
  all_joint:    False
  overlap_thresh:       0.9
  manual_init:  False
  use_k:        False
  use_r:        False
  use_s:        False
  use_t:        False
  init_r:       False
  init_s:       False
  init_t:       False
  drop_thresh:  0.005
  snap_thresh:  3
  scale_thresh: 0.03
  angle_thresh: 5.0
  debug:        False
  verbose:      True
  show: False
  show_optim:   False
  show_recon:   False
  checkpoint:   False
device: cuda
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/optimize_shapes.py", line 757, in <module>
    main()
  File "/workspace/MotionVectorization/motion_vectorization/optimize_shapes.py", line 265, in main
    time_bank = pickle.load(open(os.path.join(video_folder, 'time_bank.pkl'), 'rb'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/shapes38_None/time_bank.pkl'
PROGRAM
shapes_folder: motion_vectorization/outputs/shapes38_None/shapes

Shapes: dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36])
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/create_motion_file.py", line 187, in <module>
    main()
  File "/workspace/MotionVectorization/motion_vectorization/create_motion_file.py", line 69, in main
    shape_bank = pickle.load(open(os.path.join(arg.output_dir, f'{arg.video_name}_{arg.suffix}', 'shape_bank.pkl'), 'rb'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'motion_vectorization/outputs/shapes38_None/shape_bank.pkl'
root@ec25add1092f:/workspace/MotionVectorization# 