(motion_vectorization) root@30fb68955ee8:/workspace/MotionVectorization# conda activate motion_vectorization
conda install torchvision=0.15.2 -c pytorch -y
2 channel Terms of Service accepted
Channels:
 - pytorch
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

(motion_vectorization) root@30fb68955ee8:/workspace/MotionVectorization# ./scripts/script.sh videos/test.txt
videos/test.txt
PREPROCESS
test1
Traceback (most recent call last):
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/MotionVectorization/motion_vectorization/preprocess.py", line 2, in <module>
    import cv2
ImportError: libopenh264.so.5: cannot open shared object file: No such file or directory
RAFT
test1
python3: can't open file 'RAFT/extract_flow.py': [Errno 2] No such file or directory
videos/test.txt
CLUSTER
test1
Traceback (most recent call last):
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/MotionVectorization/motion_vectorization/extract_clusters.py", line 5, in <module>
    import cv2
ImportError: libopenh264.so.5: cannot open shared object file: No such file or directory
TRACK
Logging to motion_vectorization/logs/test1_track_29752.out
Traceback (most recent call last):
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/MotionVectorization/motion_vectorization/extract_shapes.py", line 1, in <module>
    import cv2
ImportError: libopenh264.so.5: cannot open shared object file: No such file or directory
OPTIM
Logging to motion_vectorization/logs/test1_optim_16044.out
Traceback (most recent call last):
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/MotionVectorization/motion_vectorization/optimize_shapes.py", line 7, in <module>
    import cv2
ImportError: libopenh264.so.5: cannot open shared object file: No such file or directory
PROGRAM
Traceback (most recent call last):
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/motion_vectorization/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/MotionVectorization/motion_vectorization/create_motion_file.py", line 5, in <module>
    import cv2
ImportError: libopenh264.so.5: cannot open shared object file: No such file or directory
(motion_vectorization) root@30fb68955ee8:/workspace/MotionVectorization# 