A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/workspace/MotionVectorization/RAFT/extract_flow.py", line 143, in <module>
    demo(args)
  File "/workspace/MotionVectorization/RAFT/extract_flow.py", line 80, in demo
    model = torch.nn.DataParallel(RAFT(args))
  File "/workspace/MotionVectorization/RAFT/core/raft.py", line 54, in __init__
    self.fnet = BasicEncoder(output_dim=256, norm_fn='instance', dropout=args.dropout)
  File "/workspace/MotionVectorization/RAFT/core/extractor.py", line 135, in __init__
    self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3)
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py", line 450, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py", line 137, in __init__
    self.weight = Parameter(torch.empty(
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py:137: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  self.weight = Parameter(torch.empty(
Model loaded on cuda
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/workspace/MotionVectorization/RAFT/extract_flow.py", line 143, in <module>
    demo(args)
  File "/workspace/MotionVectorization/RAFT/extract_flow.py", line 103, in demo
    image1 = load_image(imfile1)
             ^^^^^^^^^^^^^^^^^^^
  File "/workspace/MotionVectorization/RAFT/extract_flow.py", line 33, in load_image
    img = torch.from_numpy(img).permute(2, 0, 1).float()
          ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Numpy is not available
videos/test.txt
PREPROCESS
test1
RAFT
test1
Traceback (most recent call last):
  File "/workspace/MotionVectorization/RAFT/extract_flow.py", line 13, in <module>
    from core.raft import RAFT
  File "/workspace/MotionVectorization/RAFT/core/raft.py", line 6, in <module>
    from update import BasicUpdateBlock, SmallUpdateBlock
ModuleNotFoundError: No module named 'update'
videos/test.txt
CLUSTER
test1
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/extract_clusters.py", line 14, in <module>
    from .utils import *
  File "/workspace/MotionVectorization/motion_vectorization/utils.py", line 9, in <module>
    from kornia.filters import gaussian_blur2d
ModuleNotFoundError: No module named 'kornia'
TRACK
Logging to motion_vectorization/logs/test1_track_9207.out
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/extract_shapes.py", line 19, in <module>
    from .dataloader import DataLoader
  File "/workspace/MotionVectorization/motion_vectorization/dataloader.py", line 7, in <module>
    from .utils import get_numbers
  File "/workspace/MotionVectorization/motion_vectorization/utils.py", line 9, in <module>
    from kornia.filters import gaussian_blur2d
ModuleNotFoundError: No module named 'kornia'
OPTIM
Logging to motion_vectorization/logs/test1_optim_29382.out
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/optimize_shapes.py", line 20, in <module>
    from . import compositing
  File "/workspace/MotionVectorization/motion_vectorization/compositing.py", line 1, in <module>
    import kornia
ModuleNotFoundError: No module named 'kornia'
PROGRAM
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/create_motion_file.py", line 12, in <module>
    from .utils import get_numbers
  File "/workspace/MotionVectorization/motion_vectorization/utils.py", line 9, in <module>
    from kornia.filters import gaussian_blur2d
ModuleNotFoundError: No module named 'kornia'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/create_motion_file.py", line 12, in <module>
    from .utils import get_numbers
  File "/workspace/MotionVectorization/motion_vectorization/utils.py", line 9, in <module>
    from kornia.filters import gaussian_blur2d
ModuleNotFoundError: No module named 'kornia'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/motion_vectorization/full_motion_file.py", line 9, in <module>
    motion_file = json.load(open(motion_file_path, 'rb'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'motion_vectorization/outputs/test1_None/motion_file.json'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/MotionVectorization/svg_utils/create_svg_dense.py", line 3, in <module>
    import drawSvg as draw
ModuleNotFoundError: No module named 'drawSvg'
(base) root@30fb68955ee8:/workspace/MotionVectorization# 